### ISSUE TITLE
Feature_ Please Add a Link To ApkPure.com

### ISSUE THREAD

**Issue by zimo55** [archon810/toolbox-for-google-play-store-public#13] opened 2017-08-14 23:08 UTC
This is the best extension i ever used, make my job easier ,thanks.
It Would more awesome if you add a link to apkpure

**Comment by archon810** [comment] 2017-08-14 23:10
Dupe of #5.

**Closed as completed by archon810** 2017-08-14 23:10 UTC

**Comment by TroyByn** [comment] 2025-10-05 07:20
sh
sudo tar -xvf jetbrains-toolbox-*.tar.gz -C /opt/
cd /opt/jetbrains-toolbox-*/
./jetbrains-toolbox
