### ISSUE TITLE
Beta program button is always inactive

### ISSUE THREAD

**Issue by pdkpv** [archon810/toolbox-for-google-play-store-public#36] opened 2019-06-19 14:52 UTC
If the app has a beta program, a button will be added to either join or leave it - does not work

**Comment by archon810** [comment] 2019-06-19 15:34
We'll need more information on how to reproduce because it's working for me.

![Screenshot_20190619-083114](https://user-images.githubusercontent.com/469543/59779402-0d13c200-926d-11e9-8f74-8fa06eb43842.jpg)
![Screenshot_20190619-083023](https://user-images.githubusercontent.com/469543/59779403-0d13c200-926d-11e9-8678-813cdfd5e5a2.jpg)

**Comment by pdkpv** [comment] 2019-06-20 11:57
@archon810 

This problem exists for me for a month or more.
At first suggested that the reason with my software.
Therefore, I decided to reinstall Windows with wipes to version 1903.
Opened the browser and installed only this extension.
As a result, the button is visible, but visually shows that the program has no beta version. Click on this button can and gets on the page of the entry into beta testing.

Chrome Stable 75.0.3770.100
Windows 10 1903

In your Telegram account I will send a video capture so that you can assess the situation :)

**Comment by archon810** [comment] 2019-06-20 15:22
As communicated on Telegram, the current suspicion is that your browser language (Russian) may be the cause of this as we do some parsing of the beta page. Awaiting your confirmation whether the bug happens on the English page or not.

**Comment by pdkpv** [comment] 2019-06-22 13:11
After changing the language to English - the problem remained

![2019-06-22_16-08-09](https://user-images.githubusercontent.com/43634070/59964360-53388200-9508-11e9-9d3d-457ff7852575.jpg)

**Comment by archon810** [comment] 2019-06-22 15:27
@corbindavenport Hmm, any ideas?

**Comment by pdkpv** [comment] 2019-07-07 15:23
UP

**Comment by pdkpv** [comment] 2019-07-07 18:10
If you need additional information to solve a problem - I will try to help :)

**Comment by corbindavenport** [comment] 2019-07-08 02:46
The language shouldn't be an issue, as Toolbox specifically requests the English version for parsing. I can't seem to duplicate the bug either.

@pdkpv Can you do the keyboard shortcut Ctrl Shift J (on Windows) or Ctrl Option J (on Mac) to open the Dev Tools Console, and take a screenshot of what you see?

**Comment by pdkpv** [comment] 2019-07-08 08:52
@corbindavenport

![2019-07-08_11-51-46](https://user-images.githubusercontent.com/43634070/60796843-ddbee980-a176-11e9-995c-1f16612e34ac.jpg)

**Comment by pdkpv** [comment] 2019-07-21 14:17
Screenshot helped?

**Comment by corbindavenport** [comment] 2019-07-21 14:24
Hmm, I thought Toolbox forced English for the testing page, but maybe not? What language do you get when you visit one of the beta program pages? Example: https://play.google.com/apps/testing/com.twitter.android?authuser=0

**Comment by pdkpv** [comment] 2019-07-21 14:35
My default language in the browser is Russian.

https://play.google.com/apps/testing/com.twitter.android?authuser=0 - this link opens in Russian too.

When I tried to translate the interface into English - the extension did not work either (button beta testing).

**Comment by corbindavenport** [comment] 2019-07-21 14:43
Alright, then the problem should be fixed once Toolbox forces English for the beta checker page. Should be an easy fix.

**Comment by archon810** [comment] 2019-07-21 14:48
I thought we translated the beta page and forced English for this exact reason already.

**Comment by archon810** [comment] 2019-08-23 22:44
@corbindavenport Any updates here?

**Comment by pdkpv** [comment] 2019-09-04 15:56
UP

**Comment by archon810** [comment] 2019-09-06 00:04
This should be fixed in v2.6, out now. Please check and report back.

**Closed as completed by archon810** 2019-09-06 00:04 UTC
Labels: bug

**Comment by pdkpv** [comment] 2019-09-06 13:32
@archon810 

It works, thanks!

![2019-09-06_16-30-30](https://user-images.githubusercontent.com/43634070/64431837-deff8a80-d0c3-11e9-9925-f334e0c3d5cb.jpg)
