### ISSUE TITLE
Option to disable AppBrain doesn't behave as expected...

### ISSUE THREAD

**Issue by phaseburn** [archon810/toolbox-for-google-play-store-public#1] opened 2016-12-05 21:03 UTC
#### Expected behavior
When disabling the AppBrain button, I expect it to disable the AppBrain button only, leaving the other buttons enabled or disabled according to their individual preferences...

#### Actual behavior
It disables all buttons, including APKMirror, and AndroidPolice, in addition to disabling the AppBrain button.

#### Steps to reproduce the problem
Install extension, uncheck the "Enable AppBrain button" preference from the popup, reload the browser window with a Play Store listing in it.

**Comment by phaseburn** [comment] 2016-12-05 21:06
This actually seems to be a caching issue in Chrome, and a reload of the page uses cached data. A force reload of the page fixes it half the time for me. Closing/opening Chrome entirely worked after reloading the page after initially restoring the open tab. Perhaps make the Play Store page force reload upon preference change would be a good solution to this?

**Comment by archon810** [comment] 2016-12-05 21:06
I can't reproduce this. The Appbrain button doesn't load, the rest do.

Maybe something prevented the request from loading or something?

**Comment by archon810** [comment] 2016-12-05 21:08
We're currently chasing a bug where the buttons don't show up at all when many Play Store pages are open in rapid succession (or there's another variable at play?), maybe it's related to that.

**Comment by archon810** [comment] 2016-12-05 21:14
cc @corbindavenport

**Comment by phaseburn** [comment] 2016-12-05 21:14
Possibly, I notice that when it happens, the beta test snippet doesn't show up, either. Though while I have 21 tabs open total, only 1 was the Play Store. So maybe it's related to tab count or something.

**Comment by corbindavenport** [comment] 2016-12-05 21:20
I can't reproduce this either, but I know there's some code with how the buttons are injected that could potentially cause issues.

**Comment by archon810** [comment] 2016-12-13 18:32
This should be fixed in 1.0.10. Closing.

**Closed as completed by archon810** 2016-12-13 18:32 UTC
